---
- name: "Set Docker volume list for bind mounts"
  ansible.builtin.set_fact:
    _kometa_docker_mount_list:
      - source: "{{ kometa_docker_data_dir }}"
        target: "/config"
        type: "bind"
  when: "not kometa_docker_use_volumes"

- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _kometa_docker_mount_list:
      - source: "{{ kometa_docker_volume_name }}"
        target: "/config"
        type: "volume"
  when: "kometa_docker_use_volumes"

- name: "Convert created network into array of dictionary"
  ansible.builtin.set_fact:
    _kometa_docker_created_networks:
      - name: "{{ kometa_docker_network }}"
        ipv4_address: "{{ kometa_docker_network_ipv4 | default(omit) }}"
        ipv6_address: "{{ kometa_docker_network_ipv6 | default(omit) }}"
        aliases: "{{ kometa_docker_network_aliases | default(omit) }}"
  when: "kometa_docker_network_create"

- name: "Create placeholder array for created network"
  ansible.builtin.set_fact:
    _kometa_docker_created_networks: []
  when: "not kometa_docker_network_create"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _kometa_docker_all_networks: >
      {{ _kometa_docker_created_networks + kometa_docker_extra_networks }}

- name: "Define restart policy when configured to run-once"
  ansible.builtin.set_fact:
    _kometa_docker_restart_policy: "no"
  when: "kometa_docker_run_once_only"

- name: "Define restart policy when configured to run continuously"
  ansible.builtin.set_fact:
    _kometa_docker_restart_policy: "unless-stopped"
  when: "not kometa_docker_run_once_only"

- name: "Create Kometa Docker container"  # noqa: args[module]
  community.docker.docker_container:
    name: "{{ kometa_docker_name }}"
    image: "{{ kometa_docker_image_name }}:{{ kometa_docker_image_version }}"
    pull: true
    mounts: "{{ _kometa_docker_mount_list }}"
    dns_servers: "{{ kometa_docker_dns_servers | default(omit) }}"
    env:
      "KOMETA_READ_ONLY_CONFIG": "{{ kometa_docker_config_read_only | string | default(omit) }}"
      "TZ": "{{ kometa_docker_timezone }}"
    network_mode: "{{ kometa_docker_network }}"
    networks: "{{ _kometa_docker_all_networks }}"
    restart_policy: "{{ _kometa_docker_restart_policy }}"
    restart: "{{ _kometa_docker_config.changed | default(false) }}"
    memory: "{{ kometa_docker_memory }}"
    cpus: "{{ kometa_docker_cpus }}"
    command: "{{ kometa_docker_run_command | default(omit) }}"
    command_handling: "correct"
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: true
    interactive: true
    paused: false
    privileged: false
    read_only: false
    tty: true
