---
- name: "Create Docker network"
  community.docker.docker_network:
    name: "{{ kometa_docker_network }}"
    driver: "{{ kometa_docker_network_driver }}"
    enable_ipv6: "{{ kometa_docker_network_enable_ipv6 }}"
    internal: "{{ kometa_docker_network_internal }}"
    scope: "{{ kometa_docker_network_scope }}"
    ipam_config:
      - subnet: "{{ kometa_docker_network_subnet }}"
        gateway: "{{ kometa_docker_network_gateway }}"
  when: "kometa_docker_network_create"
