---
- name: "Create Kometa data directory"
  when: "not kometa_docker_use_volumes"
  ansible.builtin.file:
    name: "{{ kometa_docker_data_dir }}"
    state: "directory"
    mode: "0770"

- name: "Create Kometa Docker volume"
  when: "kometa_docker_use_volumes"
  community.docker.docker_volume:
    name: "{{ kometa_docker_volume_name }}"

- name: "Get info on Docker volume"
  when: "kometa_docker_use_volumes"
  community.docker.docker_volume_info:
    name: "{{ kometa_docker_volume_name }}"
  register: "kometa_docker_volume_info"

- name: "Build target path to Docker volume"
  when: "kometa_docker_use_volumes"
  ansible.builtin.set_fact:
    fact_kometa_docker_conf_folder:
      "{{ kometa_docker_volume_info['volume']['Mountpoint'] }}"

- name: "Build target path to conf folder for bind mount"
  when: "not kometa_docker_use_volumes"
  ansible.builtin.set_fact:
    fact_kometa_docker_conf_folder: "{{ kometa_docker_data_dir }}"

- name: "Create assets subfolder"
  ansible.builtin.file:
    name: "{{ fact_kometa_docker_conf_folder }}/assets"
    state: "directory"
    mode: "0770"

- name: "Create config file"
  ansible.builtin.template:
    src: "templates/config.yml.j2"
    dest: "{{ fact_kometa_docker_conf_folder }}/config.yml"
    mode: "0644"
  register: _kometa_docker_config
