---
- name: "Run common setup plays"
  import_playbook: "../resources/playbooks/setup.yml"

- name: "Converge execution"
  hosts: "all"
  become: true

  vars:
    kometa_docker_network_create: true
    kometa_docker_plex_url: "http://192.168.1.12:32400"
    kometa_docker_plex_token: "fake-plex-token"
    kometa_docker_tautulli_url: "http://192.168.1.12:8181"
    kometa_docker_tautulli_apikey: "fake-tautulli-apikey"
    kometa_docker_tmdb_apikey: "fake-tmdb-apikey"

  roles:
    - "organicveggie.kometa"
